apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bgex9lqda-go 
  janus-idp.io/tekton: bgex9lqda-go
  backstage.io/kubernetes-id: bgex9lqda-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bgex9lqda-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  