apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bgex9lqda-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bgex9lqda-go 
  name: bgex9lqda-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bgex9lqda-go 
